### ISSUE TITLE
Add container image verification policy

### ISSUE THREAD

**Issue by dave-tucker** [bpfman/bpfman#739]
This will likely need a protobuf change to add some things we want to validate on each image.
See: https://github.com/sigstore/docs/blob/main/content/en/verifying/verify.md#keyless-verification-using-openid-connect

Requires: https://github.com/sigstore/sigstore-rs/pull/300

For example, we might want to add some K8s YAML that says something like:

```yaml
signing:
    oidcIdentityRegexp: `"*@redhat.com"`
    oidcIssuerRegexp: "*.github.com"
```
